server:
  port: 8083
  servlet:
    contextPath: /user

spring:
  application:
    name: user
  
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
      generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

#스프링 유레카 클라이언트 구축
eureka:
  client:
    register-with-eureka: true #클라이언트로써 디스커버리 서버에 등록하는 것.
    fetch-registry: true #클라이언트로써 eureka 서버에서 eureka 레지스트리 정보를 가져올지 여부를 설정
    service-url:
      default-zone: http://localhost:8761/eureka/ #유레카 서버에 해당하는 url을 써줘야 함. 