apiVersion: v1
kind: Service
metadata:
  name: momukji-main-app
  labels:
    app: webapp
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: momukji-main-rs
spec:
  replicas: 2

  selector:
    matchLabels:
      app: webapp
      tier: app
  template:
    metadata:
      labels:
        app: webapp
        tier: app
    spec:
      containers:
        - name: momukji-main
          image: momukji-main:44437b6
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
              protocol: TCP
