name: Build on PR

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  main-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: main

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Gradle
      run: ./gradlew build
        
  auth-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: auth

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      run: ./gradlew build
        
  user-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: user

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      run: ./gradlew build