name: CI and CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Test with Gradle
      uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
      with:
        arguments: test

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_URL }}
        port: ${{ secrets_SERVER_PORT }}
        username: ${{ secrets.SERVER_ID }}
        password: ${{ secrets.SERVER_PW }}
        envs: GITHUB_SHA
        script: |
          rm -rf mo-muk-ji/
          git clone https://github.com/f-lab-edu/mo-muk-ji.git
          rm mo-muk-ji/src/main/resources/application.yml
          cp secret/application-prod.yml mo-muk-ji/src/main/resources/application.yml
          cd mo-muk-ji
          ./gradlew build -x test
          docker build -t momukji-mono:${GITHUB_SHA::7} .
          docker save momukji-mono:${GITHUB_SHA::7} | ctr -a /run/k3s/containerd/containerd.sock -n=k8s.io images import -
          cd ..
          sh change_version.sh ${GITHUB_SHA::7}
          kubectl apply -f momukji-mono.yml